#!/bin/bash -ex

# keep in sync with conf.d/main
SRC=/usr/local/src
W2PROOT=/var/www/web2py
EDENROOT=$W2PROOT/applications/eden

EDEN_URL="https://github.com/flavour/eden.git"
TWEEPY_URL="http://tweepy.googlecode.com/files/tweepy-1.4.tar.gz"

# download eden
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
git clone $EDEN_URL $EDENROOT
unset HTTP_PROXY

# download tweepy
[ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
cd $SRC; curl -L -f -O $PROXY $TWEEPY_URL; cd -

