#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src
W2PROOT=/var/www/web2py
EDENROOT=$W2PROOT/applications/eden
EDEN_URL="https://github.com/sahana/eden-stable.git"

# download eden
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
git clone $EDEN_URL $EDENROOT --depth=1
unset HTTP_PROXY

# download web2py patch - TBH not sure if this is needed, but seems to work...
PATCH_URL=http://eden.sahanafoundation.org/downloads/scheduler.diff
dl $PATCH_URL $SRC
