#!/bin/bash -ex

DB_NAME=eden
DB_USER=eden
DB_PASS=$(mcookie)

ADMIN_USERNAME=eden
ADMIN_PASSWORD=turnkey1
ADMIN_EMAIL=admin@example.com

SRC=/usr/local/src
W2PROOT=/var/www/web2py
EDENROOT=$W2PROOT/applications/eden
USER=www-data

# set Web2py to use python3
turnkey-web2py-pyver py3

# remove redundant pkgs
apt-get purge --autoremove python-mysqldb -y

# remove python venv (only need python3 for sahan-eden)
rm -r $W2PROOT/venv*
# comment out venv activation in wsgi
sed -i "\|activate_this|s|^|#|" $W2PROOT/wsgihandler.py

# install additional dependencies via pip
pip3 install pyth sgmllib3k google-api-python-client

# checkout specific required commit ID of web2py
# Current update comes from:
# https://github.com/nursix/eden_deploy_manual/blob/716dcf49ed0d1d927722b77b888cb215770caf2c/install-eden-apache-mysql.sh#L171-L172
cd $W2PROOT
# Web2py v2.21.1
git reset --hard 6da8479
git submodule update --init --recursive || true

# remove web2py example apps
rm -rf $W2PROOT/applications/welcome
rm -rf $W2PROOT/applications/examples

# patch 2.18.5 as per eden reqs - patch downloaded in conf.d/downloads
cd $W2PROOT/gluon
patch -p0 < $SRC/scheduler.diff
rm $SRC/scheduler.diff
sed -i "s|if getattr(func, 'validate', None) is Validator.validate:|if getattr(func, 'validate', None) is not Validator.validate:|" $W2PROOT/gluon/packages/dal/pydal/validators.py
sed -i "s|\['password'\]|['passwd']|" $W2PROOT/gluon/packages/dal/pydal/adapters/mysql.py

# setup matplotlib as per Sahana-Eden recommendations
mkdir -p $W2PROOT/.matplotlib
echo "os.environ['MPLCONFIGDIR'] = '$W2PROOT/.matplotlib'" >> $W2PROOT/wsgihandler.py
sed -i 's|TkAgg|Agg|' /etc/matplotlibrc

# create required directories for eden
mkdir -p $EDENROOT/{databases,sessions}
mkdir -p $EDENROOT/static/cache/chart
mkdir -p $EDENROOT/uploads/{gis_cache,images,tracks}

# configure eden as default app
cat >$W2PROOT/routes.py<<EOF
#!/usr/bin/python3
default_application = 'eden'
default_controller = 'default'
default_function = 'index'
routes_onerror = [
    ('eden/400', '!'),
    ('eden/401', '!'),
    ('eden/509', '!'),
    ('eden/*', '/eden/errors/index'),
    ('*/*', '/eden/errors/index'),
]
EOF


# setup db
service mysql start

mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# configure eden db model
CONF=$EDENROOT/models/000_config.py
cp $EDENROOT/modules/templates/000_config.py $CONF
chown www-data:www-data $CONF
chmod 640 $CONF

modify_conf() {
    sed -i "\|$1|s|^#||" $CONF
    [[ -z "$2" ]] || sed -i "\|$1|s|=.*|= $2|" $CONF
}

# initial config
sed -i "s|EDITING_CONFIG_FILE.*|EDITING_CONFIG_FILE = True|" $CONF
modify_conf "database.db_type = \"mysql\""
modify_conf "database.database =" "'$DB_NAME'"
modify_conf "database.username =" "'$DB_USER'"
modify_conf "database.password =" "'$DB_PASS'"
modify_conf "auth.hmac_key =" "'$(mcookie)'"
modify_conf "base.public_url =" "'http://127.0.0.1'"

# initialize eden and get ready for production
EDENTOOLS="applications/eden/static/scripts/tools"
cd $W2PROOT

# Remove buggy pyc file
rm gluon/contrib/plural_rules/fa.pyc
python3 web2py.py -S eden -M -R $EDENTOOLS/noop.py
python3 web2py.py -S eden -M -R $EDENTOOLS/compile.py

# sahana eden admin user created by default install

# finalise config & ensure webserver ownership
modify_conf "base.prepopulate =" 1
modify_conf "base.migrate =" False
chown -R $USER:$USER $W2PROOT

# stop services
service mysql stop
service apache2 stop
