#!/bin/sh -ex

DB_NAME=eden
DB_USER=eden
DB_PASS=$(mcookie)

SRC=/usr/local/src
W2PROOT=/var/www/web2py
EDENROOT=$W2PROOT/applications/eden

# remove web2py example apps
rm -rf $W2PROOT/applications/welcome
rm -rf $W2PROOT/applications/examples

# unpack and install tweepy
tar -zxf $SRC/tweepy-*.tar.gz -C $SRC
rm $SRC/tweepy-*.tar.gz
cd $SRC/tweepy-*
python setup.py install
cd /
rm -rf $SRC/tweepy-*

# setup matplotlib
sed -i "s|^backend      : TkAgg|backend      : Agg|" /etc/matplotlibrc
mkdir -p /var/www/.matplotlib
chown www-data:www-data /var/www/.matplotlib

# unpack eden and create required directories
tar -zxf $SRC/flavour-eden-*.tar.gz -C $W2PROOT/applications/
rm $SRC/flavour-eden-*.tar.gz
mv $W2PROOT/applications/flavour-eden-* $EDENROOT

mkdir -p $EDENROOT/static/cache/chart
mkdir -p $EDENROOT/uploads/gis_cache
mkdir -p $EDENROOT/uploads/images
mkdir -p $EDENROOT/uploads/tracks

# configure eden as default app
cat >$W2PROOT/routes.py<<EOF
#!/usr/bin/python
default_application = 'eden'
default_controller = 'default'
default_function = 'index'
routes_onerror = [
    ('eden/400', '!'),
    ('eden/401', '!'),
    ('eden/*', '/eden/errors/index'),
    ('*/*', '/eden/errors/index'),
]
EOF

chown -R www-data:www-data $W2PROOT

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

