#!/bin/bash -e
# regenerate sahana-eden secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/web2py/applications/eden/models/000_config.py

HMAC=$(mcookie)
PASSWORD=$(mcookie)

sed -i "s|auth.hmac_key.*|auth.hmac_key = \"$HMAC\"|" $CONF
sed -i "s|database.password.*|database.password = \"$PASSWORD\"|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=eden --pass="$PASSWORD"

# Now need to compile and replace the existing precompiled file...:
python3 -m compileall $CONF
PYCACHE=$(dirname $CONF)/__pycache__
COMPILED=/var/www/web2py/applications/eden/compiled/models.000_config.pyc
cp $PYCACHE/000_config.cpython-??.pyc $COMPILED
chown www-data:www-data $COMPILED
rm -rf $PYCACHE
systemctl restart apache2
