#!/bin/bash -e
# regenerate sahana-eden secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/web2py/applications/eden/models/000_config.py

HMAC=$(mcookie)
PASSWORD=$(mcookie)

sed -i "s|auth.hmac_key.*|auth.hmac_key = \"$HMAC\"|" $CONF
sed -i "s|database.password.*|database.password = \"$PASSWORD\"|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=eden --pass="$PASSWORD"

